name: Update Resume after Vercel Deployment success

on:
  deployment_status:

jobs:
  update-resume:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run script
        run: |
          cd resumeToPdf
          deno install --allow-scripts=npm:puppeteer@23.11.1 --node-modules-dir=auto
          deno run -A --node-modules-dir=auto ./index.ts

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m ":wrench: Update pdf of the resume after deployment"
            git push origin main
          fi
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
